#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// build.mjs — Claude-owned build step (render lives in index.html; this injects DATA).
//
// OWNERSHIP CONTRACT (see DIVISION-OF-LABOR / DEPLOY-PROTOCOL):
//   • Tasklet delivers DATA into data-clean/: the 4 sealed blobs (FEATURES_BY_TYPE, ROUTES,
//     STORIES, VESSEL_SPECS) + the PUBLIC-STRIPPED pitch surface (city_briefs/*.json, partners/*.json,
//     keyed by city_id / partner_id). Per SEAL.json the website build MUST bake the pitch from
//     data-clean/ — NOT partner-pitch/ (the internal, un-stripped authoring tree). Tasklet never emits index.html.
//   • Claude owns index.html (the render) + this build + deploy.
//
// This reads data-clean/ and emits atlas-data.js — a single static asset that
// sets the window.* globals index.html consumes. index.html loads it via <script src>.
// One generator of the deployable data, so a build regen can't clobber the render.
// ─────────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DC = join(ROOT, 'data-clean');        // Tasklet's sealed blobs
const PITCH = join(ROOT, 'partner-pitch');   // Tasklet's pitch source of truth (city_briefs/, partners/)
const OUT = join(ROOT, 'atlas-data.js');

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

// Assemble a {key: value} map from a directory of per-record JSON files (sorted for stable diffs).
function assembleDir(dir, keyField) {
  const out = {};
  if (!existsSync(dir)) return out;
  for (const f of readdirSync(dir).filter((n) => n.endsWith('.json')).sort()) {
    const rec = readJson(join(dir, f));
    const key = (keyField && rec[keyField]) || f.replace(/\.json$/, '');
    out[key] = rec;
  }
  return out;
}

// Sealed blobs — Tasklet's source of record (hashed by data-clean/SEAL.json). Required.
const blobs = ['FEATURES_BY_TYPE', 'ROUTES', 'STORIES', 'VESSEL_SPECS'];
const data = {};
for (const name of blobs) {
  const p = join(DC, `${name}.json`);
  if (!existsSync(p)) { console.error(`[build] FATAL: missing sealed blob data-clean/${name}.json`); process.exit(1); }
  data[name] = readJson(p);
}
// Pitch content — keyed by city_id / partner_id. MUST bake from data-clean/{city_briefs,partners}/:
// these are the PUBLIC-STRIPPED, sealed ship surface (internal + deck_only tiers removed, per
// SEAL.json.pitch.note). partner-pitch/ is the INTERNAL, un-stripped authoring tree and is also stale
// — it is only a last-resort dev fallback when the data-clean pitch surface is absent.
const briefsDir   = existsSync(join(DC, 'city_briefs')) ? join(DC, 'city_briefs') : join(PITCH, 'city_briefs');
const partnersDir = existsSync(join(DC, 'partners'))    ? join(DC, 'partners')    : join(PITCH, 'partners');
if (briefsDir.startsWith(PITCH) || partnersDir.startsWith(PITCH))
  console.warn('[build] ⚠ data-clean pitch surface missing — falling back to partner-pitch/ (INTERNAL, un-stripped). NOT valid for prod.');
data.CITY_BRIEFS = assembleDir(briefsDir, 'city_id');
data.PARTNERS = assembleDir(partnersDir, 'partner_id');
// Cluster briefs (NEW surface — country/archipelago-scale, keyed by cluster_id; each carries a `tier`:
// first-class iff a signature_route resolves to a built route, else tag-only). Baked like city_briefs.
const clusterDir = existsSync(join(DC, 'cluster_briefs')) ? join(DC, 'cluster_briefs') : join(PITCH, 'cluster_briefs');
data.CLUSTER_BRIEFS = assembleDir(clusterDir, 'cluster_id');

// Defensive strip: internal classification fields that must never reach the public artifact. The render
// never reads these. Belt-and-suspenders over Tasklet's externalizer — the 2026-06-01 P0+P1 reseal leaked
// `posture` (P0/P1/P2/Watch) + `archetype_scores` onto city features (both on the EXCLUSION blocklist).
// Stripping here keeps the sealed source intact (seal still verifies) while the deployed atlas-data.js
// stays clean. Safe to keep permanently; remove only if these ever become intended-public fields.
const STRIP_PROPS = ['posture', 'archetype_scores'];
for (const t of Object.keys(data.FEATURES_BY_TYPE || {}))
  for (const f of (data.FEATURES_BY_TYPE[t] || []))
    if (f && f.properties) for (const k of STRIP_PROPS) delete f.properties[k];

const banner = `/* GENERATED by scripts/build.mjs from data-clean/ — do not edit by hand.\n` +
  `   Tasklet delivers data into data-clean/; Claude builds this asset + deploys. */\n`;
const body = Object.entries(data)
  .map(([k, v]) => `window.${k}=${JSON.stringify(v)};`)
  .join('\n');
writeFileSync(OUT, banner + body + '\n');

const fc = data.FEATURES_BY_TYPE, ftypes = Object.keys(fc);
const nodes = ftypes.reduce((n, t) => n + (fc[t] ? fc[t].length : 0), 0);
console.log(`[build] atlas-data.js written (${(readFileSync(OUT).length / 1e6).toFixed(2)} MB)`);
console.log(`[build]   features: ${nodes} across ${ftypes.length} types · routes: ${data.ROUTES.length} · stories: ${data.STORIES.length}`);
console.log(`[build]   city briefs: ${Object.keys(data.CITY_BRIEFS).length} · partners: ${Object.keys(data.PARTNERS).length} · cluster briefs: ${Object.keys(data.CLUSTER_BRIEFS).length}`);
