#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// build-site.mjs — assemble the full deploy tree in _dist/ (v4, path-based partner pages).
//
//   node scripts/build-site.mjs
//
// Output tree (deploy _dist/ to Vercel):
//   _dist/index.html         · aggregate render (all partners; internal)
//   _dist/atlas-data.js      · full data (built from data-clean/)
//   _dist/<slug>/index.html  · per-partner render + window.__PARTNER_BUILD__ lock
//   _dist/<slug>/atlas-data.js · data SCOPED to that partner only (cities/routes/POIs/briefs/stories
//                                reachable from PARTNERS[slug].phases[].cities + only PARTNERS[slug])
//   _dist/vercel.json        · cleanUrls
//
// Isolation = scoped data (a partner page literally contains no other partner's data) + the render
// build-lock (ignores ?partner= overrides). Each partner build runs the exclusion-token grep AND a
// cross-partner sweep (no other partner's hero.title / id key); any hit ⇒ that build aborts.
//
// Pitch is baked from data-clean/{city_briefs,partners}/ (PUBLIC-STRIPPED) per SEAL.json — never partner-pitch/.
// ─────────────────────────────────────────────────────────────────────────────
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DC = path.join(ROOT, 'data-clean');
const PITCH = path.join(ROOT, 'partner-pitch');
const DIST = path.join(ROOT, '_dist');
const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));

// ---- load data (mirrors build.mjs: sealed blobs + public-stripped pitch) ----
function loadData() {
  const data = {};
  for (const name of ['FEATURES_BY_TYPE', 'ROUTES', 'STORIES', 'VESSEL_SPECS']) {
    const p = path.join(DC, `${name}.json`);
    if (!fs.existsSync(p)) { console.error(`FATAL: missing sealed blob data-clean/${name}.json`); process.exit(1); }
    data[name] = readJson(p);
  }
  const dir = (sub, keyField) => {
    const base = fs.existsSync(path.join(DC, sub)) ? path.join(DC, sub) : path.join(PITCH, sub);
    if (base.startsWith(PITCH)) console.warn(`⚠ data-clean/${sub} missing — falling back to partner-pitch/ (INTERNAL). NOT for prod.`);
    const o = {};
    if (fs.existsSync(base)) for (const fn of fs.readdirSync(base).filter(f => f.endsWith('.json')).sort()) {
      const rec = readJson(path.join(base, fn)); o[rec[keyField] || fn.replace(/\.json$/, '')] = rec;
    }
    return o;
  };
  data.CITY_BRIEFS = dir('city_briefs', 'city_id');
  data.PARTNERS = dir('partners', 'partner_id');
  return data;
}

const banner = `/* GENERATED by scripts/build-site.mjs from data-clean/ — do not edit by hand. */\n`;
const emitDataJs = (file, data) => fs.writeFileSync(file,
  banner + Object.entries(data).map(([k, v]) => `window.${k}=${JSON.stringify(v)};`).join('\n') + '\n');

// ---- city-id resolution (mirrors render _cityIdOf / _resolvePhaseCities) ----
function scoper(FBT) {
  const cityIds = new Set([...(FBT.city || []), ...(FBT.priority_city || [])].map(f => f.properties && f.properties.id).filter(Boolean));
  const nodeIndex = {}; for (const t of Object.keys(FBT)) for (const f of FBT[t]) { const p = f.properties; if (p && p.id) nodeIndex[p.id] = p; }
  const cityIdOf = (id) => {
    if (!id) return null;
    if (cityIds.has(id)) return id;
    const p = nodeIndex[id];
    if (p && cityIds.has(p.parent_city_id)) return p.parent_city_id;
    const pre = String(id).split('__')[0];
    return cityIds.has(pre) ? pre : null;
  };
  const resolve = (loose) => {
    const out = new Set();
    for (const c of (loose || [])) {
      if (cityIds.has(c)) { out.add(c); continue; }
      const x = String(c).toLowerCase();
      for (const id of cityIds) { const a = id.toLowerCase(); if (a === x || a.startsWith(x + '-') || a.startsWith(x + '_') || a.split(/[-_]/).includes(x)) out.add(id); }
    }
    return out;
  };
  return { cityIds, cityIdOf, resolve };
}

// ---- scope the full data object to one partner ----
// opts: { keepCities?, expandRegion=true, routesWithin=false } — a hub index passes all markets' cities
// (anchors-only, no region expansion, intra-anchor routes); a market deep-dive passes that market's cities.
function scopeForPartner(data, slug, opts = {}) {
  const partner = data.PARTNERS[slug];
  const { cityIdOf, resolve } = scoper(data.FEATURES_BY_TYPE);
  const keep = new Set();   // the page's footprint (phase cities by default; markets' cities for a hub)
  const citySrc = opts.keepCities || [].concat(...((partner.phases || []).map(ph => ph.cities || [])));
  for (const c of resolve(citySrc)) keep.add(c);
  if (!keep.size) return { error: 'no cities resolved' };

  // End-state network = every city in the same REGION(s) as the rollout. The base atlas
  // (cities + routes) is public / non-partner-private, so a partner page can show the whole regional
  // network it could become — only the PITCH (PARTNERS/STORIES/overlays/briefs) stays scoped. Region
  // labels are inconsistent upstream (SEA vs Southeast Asia, …), so alias-merge before comparing.
  const normReg = (r) => { const k = String(r || '').trim().toLowerCase();
    return ({ 'sea': 'sea', 'southeast asia': 'sea', 'caribbean': 'latam-caribbean', 'latam-caribbean': 'latam-caribbean' })[k] || k; };
  const cityRegion = {};
  for (const t of ['city', 'priority_city']) for (const f of (data.FEATURES_BY_TYPE[t] || [])) { const p = f.properties || {}; if (p.id) cityRegion[p.id] = normReg(p.region); }
  const partnerRegions = new Set([...keep].map(id => cityRegion[id]).filter(Boolean));
  const net = new Set(keep);   // NETWORK footprint = rollout cities ∪ all cities in those regions
  if (opts.expandRegion !== false && partnerRegions.size) for (const [id, reg] of Object.entries(cityRegion)) if (reg && partnerRegions.has(reg)) net.add(id);

  // ROUTES + city dots span the whole regional NETWORK (drives the end-state map). Boarding-point
  // POIs stay scoped to the rollout cities (keep) — keeps the bundle lean + the detail meaningful.
  const ROUTES = (data.ROUTES || []).filter(f => { const p = f.properties || {}; const a = net.has(cityIdOf(p.from)), b = net.has(cityIdOf(p.to)); return opts.routesWithin ? (a && b) : (a || b); });
  const phaseEndpoints = new Set();
  for (const f of (data.ROUTES || [])) { const p = f.properties || {}; if (keep.has(cityIdOf(p.from)) || keep.has(cityIdOf(p.to))) { if (p.from) phaseEndpoints.add(p.from); if (p.to) phaseEndpoints.add(p.to); } }
  const FEATURES_BY_TYPE = {};
  for (const t of Object.keys(data.FEATURES_BY_TYPE)) {
    FEATURES_BY_TYPE[t] = data.FEATURES_BY_TYPE[t].filter(f => { const p = f.properties || {};
      if (t === 'city' || t === 'priority_city') return net.has(p.id);          // full regional network of city dots
      return keep.has(p.parent_city_id) || phaseEndpoints.has(p.id); });        // POIs: partner footprint only
  }
  // Keep this partner's cities' briefs, but STRIP partner_overlays to only this partner's overlay
  // (a brief carries overlays for every partner — others must not leak onto an isolated partner page).
  const CITY_BRIEFS = {};
  for (const [cid, b] of Object.entries(data.CITY_BRIEFS)) if (keep.has(cid)) {
    const c = { ...b };
    if (c.partner_overlays) c.partner_overlays = c.partner_overlays[slug] ? { [slug]: c.partner_overlays[slug] } : {};
    CITY_BRIEFS[cid] = c;
  }
  // Only THIS partner's own story (slug == partner_id). Scoping by shared-city overlap would pull
  // another partner's story (which embeds their hero/identity) onto an isolated page.
  const STORIES = (data.STORIES || []).filter(s => s.slug === slug);
  const scoped = { FEATURES_BY_TYPE, ROUTES, STORIES, VESSEL_SPECS: data.VESSEL_SPECS, CITY_BRIEFS, PARTNERS: { [slug]: partner } };
  const cityCount = (FEATURES_BY_TYPE.city || []).length + (FEATURES_BY_TYPE.priority_city || []).length;
  return { scoped, keep: [...keep], counts: { cities: cityCount, rollout: keep.size, pois: (FEATURES_BY_TYPE.poi || []).length, routes: ROUTES.length, briefs: Object.keys(CITY_BRIEFS).length, stories: STORIES.length } };
}

// ---- safety sweep on the emitted data text ----
const tokens = (() => {
  const f = path.join(ROOT, 'docs', 'EXCLUSION-TOKENS.txt');
  return fs.existsSync(f) ? fs.readFileSync(f, 'utf8').split('\n').map(l => l.trim()).filter(l => l && !l.startsWith('#')) : [];
})();
const allowPhrases = (() => {                       // vetted phrases neutralized before the token sweep
  const f = path.join(ROOT, 'docs', 'EXCLUSION-ALLOWLIST.txt');
  return fs.existsSync(f) ? fs.readFileSync(f, 'utf8').split('\n').map(l => l.trim()).filter(l => l && !l.startsWith('#')) : [];
})();
function sweep(text, data, slug) {
  let scan = text;
  for (const ph of allowPhrases) scan = scan.replace(new RegExp(ph.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi'), ' ');
  const leaks = tokens.filter(t => { try { return new RegExp(t, 'i').test(scan); } catch { return false; } });
  const cross = [];
  for (const [pid, pr] of Object.entries(data.PARTNERS)) { if (pid === slug) continue;
    if ((pr.hero && pr.hero.title && text.includes(pr.hero.title)) || text.includes('"' + pid + '":')) cross.push(pid); }
  return { leaks, cross };
}

// ─── build ──────────────────────────────────────────────────────────────────
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });
const data = loadData();
const indexHtml = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// aggregate (all partners)
fs.writeFileSync(path.join(DIST, 'index.html'), indexHtml);
emitDataJs(path.join(DIST, 'atlas-data.js'), data);
fs.writeFileSync(path.join(DIST, 'vercel.json'), JSON.stringify({ cleanUrls: true, trailingSlash: false }, null, 2) + '\n');
console.log(`aggregate → _dist/  (${Object.keys(data.CITY_BRIEFS).length} briefs · ${Object.keys(data.PARTNERS).length} partners · ${data.ROUTES.length} routes)`);

// per-partner (path-based: _dist/<slug>/ ; hub markets at _dist/<slug>/<market.slug>/)
let failed = 0, pages = 0;
// Emit one scoped+locked page. subdir '' = bare /<slug>; marketSlug sets the __PARTNER_MARKET__ lock so
// the render opens that market's deep-dive directly. Sweeps the data text; writes only if clean.
function emitPage(slug, subdir, r, marketSlug) {
  const tag = `/${slug}${subdir ? '/' + subdir : ''}`;
  if (r.error) { console.error(`  ✗ ${tag}: ${r.error}`); failed++; return; }
  const dataText = banner + Object.entries(r.scoped).map(([k, v]) => `window.${k}=${JSON.stringify(v)};`).join('\n') + '\n';
  // Load the SCOPED data by ABSOLUTE path. With cleanUrls (no trailing slash) a relative "atlas-data.js"
  // would resolve to /atlas-data.js (the full aggregate) — defeating isolation. Use the page's own path.
  let lock = `<script>window.__PARTNER_BUILD__=${JSON.stringify(slug)};`;
  if (marketSlug) lock += `window.__PARTNER_MARKET__=${JSON.stringify(marketSlug)};`;
  lock += `</script>\n`;
  let html = indexHtml.replace('<script src="atlas-data.js"></script>', lock + `<script src="${tag}/atlas-data.js"></script>`);
  if (html === indexHtml) { console.error(`  ✗ ${tag}: could not inject lock (atlas-data.js script tag not found)`); failed++; return; }
  // Zero PARTNER_VIEWS — the lock + scoped PARTNERS[slug] drive activation, so a locked build needs none.
  const beforePV = html;
  html = html.replace(/const PARTNER_VIEWS = \{[\s\S]*?\n\};/, 'const PARTNER_VIEWS = {};');
  if (html === beforePV) { console.error(`  ✗ ${tag}: could not scope PARTNER_VIEWS (regex no match)`); failed++; return; }
  const { leaks, cross } = sweep(dataText, data, slug);
  if (leaks.length || cross.length) { console.error(`  ✗ ${tag}: ABORT sweep — tokens:[${leaks.join(',')}] cross-partner:[${cross.join(',')}]`); failed++; return; }
  const outDir = path.join(DIST, slug, subdir || '');
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'index.html'), html);
  fs.writeFileSync(path.join(outDir, 'atlas-data.js'), dataText);
  const c = r.counts;
  console.log(`  ✓ ${tag}  network cities:${c.cities} (rollout ${c.rollout}) pois:${c.pois} routes:${c.routes} briefs:${c.briefs} stories:${c.stories}`);
  pages++;
}
const marketCities = (m) => [].concat(m.anchor_cities || [], ...((m.phases || []).map(ph => ph.cities || [])));
for (const slug of Object.keys(data.PARTNERS)) {
  const partner = data.PARTNERS[slug];
  if (partner.layout === 'hub' && partner.markets && partner.markets.length) {
    // index landing: every market's cities (anchors only, no region sprawl, intra-anchor routes) → global map
    const anchors = [].concat(...partner.markets.map(marketCities));
    emitPage(slug, '', scopeForPartner(data, slug, { keepCities: anchors, expandRegion: false, routesWithin: true }), null);
    // each market = its own scoped deep-dive page (regional network like a single partner)
    for (const m of partner.markets) emitPage(slug, m.slug, scopeForPartner(data, slug, { keepCities: marketCities(m) }), m.slug);
  } else {
    emitPage(slug, '', scopeForPartner(data, slug), null);
  }
}
if (failed) { console.error(`\nbuild-site: ${failed} page build(s) failed — see above.`); process.exit(1); }
console.log(`\n_dist/ ready: 1 aggregate + ${pages} partner/market pages.`);
