#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// build-site.mjs — assemble the full deploy tree in _dist/ (v4, path-based partner pages).
//
//   node scripts/build-site.mjs
//
// Output tree (deploy _dist/ to Vercel):
//   _dist/index.html         · aggregate render (all partners; internal)
//   _dist/atlas-data.js      · full data (built from data-clean/)
//   _dist/<slug>/index.html  · per-partner render + window.__PARTNER_BUILD__ lock
//   _dist/<slug>/atlas-data.js · data SCOPED to that partner only (cities/routes/POIs/briefs/stories
//                                reachable from PARTNERS[slug].phases[].cities + only PARTNERS[slug])
//   _dist/vercel.json        · cleanUrls + api/og builds
//   _dist/middleware.js      · per-partner password gate (cluster/city share links stay public)
//
// Isolation = scoped data (a partner page literally contains no other partner's data) + the render
// build-lock (ignores ?partner= overrides). Each partner build runs the exclusion-token grep AND a
// cross-partner sweep (no other partner's hero.title / id key); any hit ⇒ that build aborts.
//
// Pitch is baked from data-clean/{city_briefs,partners}/ (PUBLIC-STRIPPED) per SEAL.json — never partner-pitch/.
// ─────────────────────────────────────────────────────────────────────────────
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  SITE_URL, injectShareMeta, clusterMeta, cityMeta, partnerMeta, trunc,
} from './share-meta.mjs';
import { generatePartnerAuthMiddleware } from './partner-auth-middleware.mjs';
import { parseProfile, applyProfile, normalizeRouteBlob } from './build-profile.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DC = path.join(ROOT, 'data-clean');
const PITCH = path.join(ROOT, 'partner-pitch');
const DIST = path.join(ROOT, '_dist');
const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));

// ---- load data (mirrors build.mjs: sealed blobs + public-stripped pitch) ----
function loadData() {
  const data = {};
  for (const name of ['FEATURES_BY_TYPE', 'ROUTES', 'STORIES', 'VESSEL_SPECS']) {
    const p = path.join(DC, `${name}.json`);
    if (!fs.existsSync(p)) { console.error(`FATAL: missing sealed blob data-clean/${name}.json`); process.exit(1); }
    let blob = readJson(p);
    if (name === 'ROUTES') blob = normalizeRouteBlob(blob);
    data[name] = blob;
  }
  const dir = (sub, keyField) => {
    const base = fs.existsSync(path.join(DC, sub)) ? path.join(DC, sub) : path.join(PITCH, sub);
    if (base.startsWith(PITCH)) console.warn(`⚠ data-clean/${sub} missing — falling back to partner-pitch/ (INTERNAL). NOT for prod.`);
    const o = {};
    if (fs.existsSync(base)) for (const fn of fs.readdirSync(base).filter(f => f.endsWith('.json')).sort()) {
      const rec = readJson(path.join(base, fn)); o[rec[keyField] || fn.replace(/\.json$/, '')] = rec;
    }
    return o;
  };
  // Belt-and-suspenders: strip internal partner tiers if Tasklet's externalizer missed them.
  const sanitizePartner = (rec) => {
    if (!rec || typeof rec !== 'object') return rec;
    const { deck_only, reviewer_notes, ...rest } = rec;
    return rest;
  };
  data.CITY_BRIEFS = dir('city_briefs', 'city_id');
  data.PARTNERS = Object.fromEntries(
    Object.entries(dir('partners', 'partner_id')).map(([k, v]) => [k, sanitizePartner(v)])
  );
  // Cluster lookup — used to scope a partner's network by the countries/clusters it touches. Optional.
  const clp = path.join(DC, 'CLUSTERS.json');
  data.CLUSTERS = fs.existsSync(clp) ? readJson(clp) : { clusters: [] };
  data.CLUSTER_BRIEFS = dir('cluster_briefs', 'cluster_id');
  // Route unit-economics sidecar → {route_id: record} (so partner pages can show the per-corridor card + dots).
  const ep = path.join(DC, 'economics_by_route_id.json');
  data.ROUTE_ECONOMICS = {};
  if (fs.existsSync(ep)) { const e = readJson(ep); for (const r of (e.records || [])) if (r && r.route_id) data.ROUTE_ECONOMICS[r.route_id] = r; }
  // Defensive strip of internal classification fields (see build.mjs) — keeps the deployed aggregate AND
  // every scoped partner page clean of `posture`/`archetype_scores`; the render never uses them.
  for (const t of Object.keys(data.FEATURES_BY_TYPE || {}))
    for (const f of (data.FEATURES_BY_TYPE[t] || []))
      if (f && f.properties) { delete f.properties.posture; delete f.properties.archetype_scores; }
  return data;
}

const banner = `/* GENERATED by scripts/build-site.mjs from data-clean/ — do not edit by hand. */\n`;
const emitDataJs = (file, data) => fs.writeFileSync(file,
  banner + Object.entries(data).map(([k, v]) => `window.${k}=${JSON.stringify(v)};`).join('\n') + '\n');

// ---- city-id resolution (mirrors render _cityIdOf / _resolvePhaseCities) ----
function scoper(FBT) {
  const cityIds = new Set([...(FBT.city || []), ...(FBT.priority_city || [])].map(f => f.properties && f.properties.id).filter(Boolean));
  const nodeIndex = {}; for (const t of Object.keys(FBT)) for (const f of FBT[t]) { const p = f.properties; if (p && p.id) nodeIndex[p.id] = p; }
  const cityIdOf = (id) => {
    if (!id) return null;
    if (cityIds.has(id)) return id;
    const p = nodeIndex[id];
    if (p && cityIds.has(p.parent_city_id)) return p.parent_city_id;
    const pre = String(id).split('__')[0];
    return cityIds.has(pre) ? pre : null;
  };
  const resolve = (loose) => {
    const out = new Set();
    for (const c of (loose || [])) {
      if (cityIds.has(c)) { out.add(c); continue; }
      const x = String(c).toLowerCase();
      for (const id of cityIds) { const a = id.toLowerCase(); if (a === x || a.startsWith(x + '-') || a.startsWith(x + '_') || a.split(/[-_]/).includes(x)) out.add(id); }
    }
    return out;
  };
  return { cityIds, cityIdOf, resolve };
}

// ---- scope the full data object to one partner ----
// opts: { keepCities?, expandRegion=true, routesWithin=false } — a hub index passes all markets' cities
// (anchors-only, no region expansion, intra-anchor routes); a market deep-dive passes that market's cities.
function scopeForPartner(data, slug, opts = {}) {
  const partner = data.PARTNERS[slug];
  const { cityIdOf, resolve } = scoper(data.FEATURES_BY_TYPE);
  const keep = new Set();   // the page's footprint (phase cities by default; markets' cities for a hub)
  const citySrc = opts.keepCities || [].concat(...((partner.phases || []).map(ph => ph.cities || [])));
  for (const c of resolve(citySrc)) keep.add(c);
  if (!keep.size) return { error: 'no cities resolved' };

  // End-state network = every city in the same REGION(s) as the rollout. The base atlas
  // (cities + routes) is public / non-partner-private, so a partner page can show the whole regional
  // network it could become — only the PITCH (PARTNERS/STORIES/overlays/briefs) stays scoped. Region
  // labels are inconsistent upstream (SEA vs Southeast Asia, …), so alias-merge before comparing.
  const normReg = (r) => { const k = String(r || '').trim().toLowerCase();
    return ({ 'sea': 'sea', 'southeast asia': 'sea', 'caribbean': 'latam-caribbean', 'latam-caribbean': 'latam-caribbean' })[k] || k; };
  const cityRegion = {}, cityCluster = {};
  for (const t of ['city', 'priority_city']) for (const f of (data.FEATURES_BY_TYPE[t] || [])) { const p = f.properties || {}; if (p.id) { cityRegion[p.id] = normReg(p.region); cityCluster[p.id] = p.cluster_id || null; } }
  // CLUSTERS.member_city_ids is the authoritative, 100%-complete city→cluster map (the city-node cluster_id
  // property lags it). Prefer it so EVERY city resolves to a cluster, then fall back to the node property.
  for (const c of ((data.CLUSTERS && data.CLUSTERS.clusters) || [])) for (const id of (c.member_city_ids || [])) if (id in cityCluster) cityCluster[id] = c.cluster_id;
  // Expand the NETWORK footprint precisely: by CLUSTER (country/archipelago) where the rollout cities are
  // cluster-tagged — so a Grab Taiwan market doesn't drag in all of Japan/Korea the way coarse continental
  // region-expansion did. Fall back to region ONLY for rollout cities not yet cluster-tagged upstream
  // (~25%), so coverage never regresses while tagging completes.
  const partnerClusters = new Set([...keep].map(id => cityCluster[id]).filter(Boolean));
  const fallbackRegions = new Set([...keep].filter(id => !cityCluster[id]).map(id => cityRegion[id]).filter(Boolean));
  const net = new Set(keep);   // NETWORK footprint = rollout cities ∪ cities in those clusters (∪ region fallback)
  if (opts.expandRegion !== false) for (const id of Object.keys(cityRegion)) {
    if (cityCluster[id] ? partnerClusters.has(cityCluster[id]) : fallbackRegions.has(cityRegion[id])) net.add(id);
  }

  // ROUTES + city dots span the whole regional NETWORK (drives the end-state map). Boarding-point
  // POIs stay scoped to the rollout cities (keep) — keeps the bundle lean + the detail meaningful.
  const ROUTES = (data.ROUTES || []).filter(f => { const p = f.properties || {}; const a = net.has(cityIdOf(p.from)), b = net.has(cityIdOf(p.to)); return opts.routesWithin ? (a && b) : (a || b); });
  const phaseEndpoints = new Set();
  for (const f of (data.ROUTES || [])) { const p = f.properties || {}; if (keep.has(cityIdOf(p.from)) || keep.has(cityIdOf(p.to))) { if (p.from) phaseEndpoints.add(p.from); if (p.to) phaseEndpoints.add(p.to); } }
  const FEATURES_BY_TYPE = {};
  for (const t of Object.keys(data.FEATURES_BY_TYPE)) {
    FEATURES_BY_TYPE[t] = data.FEATURES_BY_TYPE[t].filter(f => { const p = f.properties || {};
      if (t === 'city' || t === 'priority_city') return net.has(p.id);          // full regional network of city dots
      return keep.has(p.parent_city_id) || phaseEndpoints.has(p.id); });        // POIs: partner footprint only
  }
  // Keep this partner's cities' briefs, but STRIP partner_overlays to only this partner's overlay
  // (a brief carries overlays for every partner — others must not leak onto an isolated partner page).
  const CITY_BRIEFS = {};
  for (const [cid, b] of Object.entries(data.CITY_BRIEFS)) if (keep.has(cid)) {
    const c = { ...b };
    if (c.partner_overlays) c.partner_overlays = c.partner_overlays[slug] ? { [slug]: c.partner_overlays[slug] } : {};
    CITY_BRIEFS[cid] = c;
  }
  // Only THIS partner's own story (slug == partner_id). Scoping by shared-city overlap would pull
  // another partner's story (which embeds their hero/identity) onto an isolated page.
  const STORIES = (data.STORIES || []).filter(s => s.slug === slug);
  // Per-corridor economics for routes ON THIS PAGE — isolation-safe: only THIS partner's own records
  // (rec.partner === slug), so the unit-economics card + gold dots work on the partner page without
  // surfacing another partner's modeled corridors.
  const routeIds = new Set(ROUTES.map(f => f.properties && f.properties.id));
  const ROUTE_ECONOMICS = {};
  for (const [rid, rec] of Object.entries(data.ROUTE_ECONOMICS || {})) if (routeIds.has(rid) && rec.partner === slug) ROUTE_ECONOMICS[rid] = rec;
  // Clusters touching this page's network (geographic, not partner-private) → cluster pins / breadcrumb /
  // "Part of {cluster}" + their briefs. Scoped to relevant clusters for relevance + leanness.
  const clusters = (((data.CLUSTERS || {}).clusters) || []).filter(c => (c.member_city_ids || []).some(id => net.has(id)));
  const CLUSTERS = { ...(data.CLUSTERS || {}), clusters };
  const clIds = new Set(clusters.map(c => c.cluster_id));
  const CLUSTER_BRIEFS = {};
  for (const [cid, brief] of Object.entries(data.CLUSTER_BRIEFS || {})) if (clIds.has(cid)) CLUSTER_BRIEFS[cid] = brief;
  const scoped = { FEATURES_BY_TYPE, ROUTES, STORIES, VESSEL_SPECS: data.VESSEL_SPECS, CITY_BRIEFS, PARTNERS: { [slug]: partner }, ROUTE_ECONOMICS, CLUSTERS, CLUSTER_BRIEFS };
  const cityCount = (FEATURES_BY_TYPE.city || []).length + (FEATURES_BY_TYPE.priority_city || []).length;
  return { scoped, keep: [...keep], counts: { cities: cityCount, rollout: keep.size, pois: (FEATURES_BY_TYPE.poi || []).length, routes: ROUTES.length, briefs: Object.keys(CITY_BRIEFS).length, stories: STORIES.length } };
}

// ---- safety sweep on the emitted data text ----
const tokens = (() => {
  const f = path.join(ROOT, 'docs', 'EXCLUSION-TOKENS.txt');
  return fs.existsSync(f) ? fs.readFileSync(f, 'utf8').split('\n').map(l => l.trim()).filter(l => l && !l.startsWith('#')) : [];
})();
const allowPhrases = (() => {                       // vetted phrases neutralized before the token sweep
  const f = path.join(ROOT, 'docs', 'EXCLUSION-ALLOWLIST.txt');
  return fs.existsSync(f) ? fs.readFileSync(f, 'utf8').split('\n').map(l => l.trim()).filter(l => l && !l.startsWith('#')) : [];
})();
function sweep(text, data, slug) {
  let scan = text;
  for (const ph of allowPhrases) scan = scan.replace(new RegExp(ph.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi'), ' ');
  const leaks = tokens.filter(t => { try { return new RegExp(t, 'i').test(scan); } catch { return false; } });
  const cross = [];
  for (const [pid, pr] of Object.entries(data.PARTNERS)) { if (pid === slug) continue;
    // Detect another partner's RECORD leaking in (its identity prose, or its keyed partner_id). Match on
    // "partner_id":"<pid>" — NOT a bare "<pid>": key — so a city that shares an id with a partner (e.g. the
    // Hong Kong city vs the hong-kong partner) doesn't false-positive when a page legitimately includes it.
    if ((pr.hero && pr.hero.title && text.includes(pr.hero.title)) || text.includes('"partner_id":"' + pid + '"')) cross.push(pid); }
  return { leaks, cross };
}

// ─── build ──────────────────────────────────────────────────────────────────
fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });
const profile = parseProfile();
const data = loadData();
const aggregateData = applyProfile(data, profile);
const indexHtml = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');

// aggregate — public profile strips partner/story data; internal keeps full admin surface
const aggregateMeta = partnerMeta({ display: 'Navier Atlas', partner_id: 'atlas', hero: { title: 'Navier Atlas · Mobility Network', subtitle: 'Interactive map of the electric-hydrofoil mobility network.' }, region: 'Global' });
let aggregateHtml = injectShareMeta(indexHtml, { ...aggregateMeta, canonicalPath: '/' });
if (profile === 'public') {
  aggregateHtml = aggregateHtml.replace(
    '<script src="atlas-data.js"></script>',
    '<script>window.__PUBLIC_BUILD__=true;</script>\n<script src="atlas-data.js"></script>'
  );
}
fs.writeFileSync(path.join(DIST, 'index.html'), aggregateHtml);
emitDataJs(path.join(DIST, 'atlas-data.js'), aggregateData);

// Vercel OG image API + install hook for @vercel/og
const apiSrc = path.join(ROOT, 'api');
const apiDst = path.join(DIST, 'api');
if (fs.existsSync(apiSrc)) {
  fs.mkdirSync(apiDst, { recursive: true });
  for (const fn of fs.readdirSync(apiSrc)) fs.copyFileSync(path.join(apiSrc, fn), path.join(apiDst, fn));
}
fs.writeFileSync(path.join(DIST, 'package.json'), JSON.stringify({
  private: true,
  type: 'module',
  dependencies: { '@vercel/functions': '^2.0.0', '@vercel/og': '^0.6.8', react: '^18.3.1' },
}, null, 2) + '\n');
// No legacy `builds`/`routes` — they bypass Edge middleware on partner paths.
// Vercel auto-serves api/og.js as a function, static files from the tree, middleware.js on the edge.
fs.writeFileSync(path.join(DIST, 'vercel.json'), JSON.stringify({
  version: 2,
  cleanUrls: true,
  trailingSlash: false,
  installCommand: 'npm install --omit=dev',
}, null, 2) + '\n');
const partnerSlugs = Object.keys(data.PARTNERS).sort();
fs.writeFileSync(path.join(DIST, 'middleware.js'), generatePartnerAuthMiddleware(partnerSlugs));
console.log(`aggregate → _dist/  profile:${profile} · ${Object.keys(aggregateData.CITY_BRIEFS).length} briefs · ${partnerSlugs.length} partner pages · ${aggregateData.ROUTES.length} routes)`);
console.log(`middleware → _dist/middleware.js  (${partnerSlugs.length} partner matchers; /cluster/ + /city/ public)`);

// per-partner (path-based: _dist/<slug>/ ; hub markets at _dist/<slug>/<market.slug>/)
let failed = 0, pages = 0, skipped = 0, sharePages = 0;

function injectPage(html, lockScripts, dataJsAbs, shareRoute, meta, canonicalPath) {
  let h = meta ? injectShareMeta(html, { ...meta, canonicalPath }) : html;
  let scripts = (lockScripts || '');
  if (shareRoute) scripts += `<script>window.__SHARE_ROUTE__=${JSON.stringify(shareRoute)};</script>\n`;
  scripts += `<script src="${dataJsAbs}"></script>`;
  h = h.replace('<script src="atlas-data.js"></script>', scripts);
  if (lockScripts) {
    const beforePV = h;
    h = h.replace(/const PARTNER_VIEWS = \{[\s\S]*?\n\};/, 'const PARTNER_VIEWS = {};');
    if (h === beforePV) console.warn('  ⚠ could not scope PARTNER_VIEWS on', canonicalPath);
  }
  return h;
}

function writeShareTree(relDir, html, dataJsAbs, shareRoute, meta, lockScripts) {
  const canonicalPath = `/${relDir.split(path.sep).join('/')}`;
  const outDir = path.join(DIST, relDir);
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'index.html'), injectPage(html, lockScripts || '', dataJsAbs, shareRoute, meta, canonicalPath));
  sharePages++;
}

// Emit one scoped+locked page. subdir '' = bare /<slug>; marketSlug sets the __PARTNER_MARKET__ lock so
// the render opens that market's deep-dive directly. Sweeps the data text; writes only if clean.
function emitPage(slug, subdir, r, marketSlug, optional, pageMeta) {
  const tag = `/${slug}${subdir ? '/' + subdir : ''}`;
  // A hub MARKET sub-page that can't resolve its cities (market anchor_cities reference nodes not in the
  // atlas) is skipped with a warning rather than failing the whole deploy — the hub index still lists the
  // market and the in-aggregate deep-dive still renders from pitch. (Flag the bad anchor_cities to Tasklet.)
  if (r.error) { if (optional) { console.warn(`  ⚠ skip ${tag}: ${r.error}`); skipped++; } else { console.error(`  ✗ ${tag}: ${r.error}`); failed++; } return; }
  const dataText = banner + Object.entries(r.scoped).map(([k, v]) => `window.${k}=${JSON.stringify(v)};`).join('\n') + '\n';
  let lock = `<script>window.__PARTNER_BUILD__=${JSON.stringify(slug)};`;
  if (marketSlug) lock += `window.__PARTNER_MARKET__=${JSON.stringify(marketSlug)};`;
  lock += `</script>\n`;
  const html = injectPage(indexHtml, lock, `${tag}/atlas-data.js`, null, pageMeta, tag);
  if (!html.includes('__PARTNER_BUILD__')) { console.error(`  ✗ ${tag}: could not inject lock`); failed++; return; }
  const { leaks, cross } = sweep(dataText, data, slug);
  if (leaks.length || cross.length) { console.error(`  ✗ ${tag}: ABORT sweep — tokens:[${leaks.join(',')}] cross-partner:[${cross.join(',')}]`); failed++; return; }
  const outDir = path.join(DIST, slug, subdir || '');
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, 'index.html'), html);
  fs.writeFileSync(path.join(outDir, 'atlas-data.js'), dataText);
  const c = r.counts;
  console.log(`  ✓ ${tag}  network cities:${c.cities} (rollout ${c.rollout}) pois:${c.pois} routes:${c.routes} briefs:${c.briefs} stories:${c.stories}`);
  pages++;
}
const marketCities = (m) => [].concat(m.anchor_cities || [], ...((m.phases || []).map(ph => ph.cities || [])));
for (const slug of Object.keys(data.PARTNERS)) {
  const partner = data.PARTNERS[slug];
  if ((partner.layout === 'hub' || partner.layout === 'network') && partner.markets && partner.markets.length) {
    const anchors = [].concat(...partner.markets.map(marketCities));
    emitPage(slug, '', scopeForPartner(data, slug, { keepCities: anchors }), null, false, partnerMeta(partner));
    for (const m of partner.markets) {
      const scoped = scopeForPartner(data, slug, { keepCities: marketCities(m) });
      emitPage(slug, m.slug, scoped, m.slug, true, partnerMeta(partner, m));
      // Per-city share pages under each market (e.g. /grab/penang/city/langkawi-malaysia).
      if (!scoped.error) {
        for (const cid of scoped.keep) {
          const brief = data.CITY_BRIEFS[cid];
          if (!brief) continue;
          const props = (data.FEATURES_BY_TYPE.city || []).concat(data.FEATURES_BY_TYPE.priority_city || [])
            .map(f => f.properties).find(p => p && p.id === cid) || { id: cid, name: brief.display || cid };
          const rel = path.join(slug, m.slug, 'city', cid);
          const lock = `<script>window.__PARTNER_BUILD__=${JSON.stringify(slug)};window.__PARTNER_MARKET__=${JSON.stringify(m.slug)};</script>\n`;
          const cm = cityMeta(brief, props);
          cm.title = `${partner.display || slug} · ${props.name || brief.display || cid}`;
          // City shells use brief tagline/summary (cityMeta); market summary belongs on /partner/market only.
          cm.ogBadge = m.label || m.region || cm.ogBadge;
          writeShareTree(rel, indexHtml, `/${slug}/${m.slug}/atlas-data.js`,
            { type: 'city', id: cid, partner: slug, market: m.slug }, cm, lock);
        }
      }
    }
  } else {
    emitPage(slug, '', scopeForPartner(data, slug), null, false, partnerMeta(partner));
  }
}

// Aggregate cluster + city share pages (path-based deeplinks + OG previews).
const clusterById = Object.fromEntries(((data.CLUSTERS.clusters) || []).map(c => [c.cluster_id, c]));
for (const [cid, cb] of Object.entries(data.CLUSTER_BRIEFS)) {
  writeShareTree(path.join('cluster', cid), indexHtml, '/atlas-data.js',
    { type: 'cluster', id: cid }, clusterMeta(cb, clusterById[cid]));
}
for (const [cityId, brief] of Object.entries(data.CITY_BRIEFS)) {
  const props = (data.FEATURES_BY_TYPE.city || []).concat(data.FEATURES_BY_TYPE.priority_city || [])
    .map(f => f.properties).find(p => p && p.id === cityId) || { id: cityId, name: brief.display || cityId };
  writeShareTree(path.join('city', cityId), indexHtml, '/atlas-data.js',
    { type: 'city', id: cityId }, cityMeta(brief, props));
}

if (failed) { console.error(`\nbuild-site: ${failed} page build(s) failed — see above.`); process.exit(1); }
console.log(`\n_dist/ ready: 1 aggregate + ${pages} partner/market + ${sharePages} share pages${skipped?` (${skipped} market sub-page(s) skipped)`:''}.`);
console.log(`Share URLs: ${SITE_URL}/cluster/<id> · ${SITE_URL}/city/<id> · ${SITE_URL}/<partner>/<market>/city/<id>`);
