#!/usr/bin/env python3
"""City briefs for the new MX/EG markets — data-clean schema, partner-facing plain English.
Emits to partner-pitch/city_briefs/ (data-clean seal = straight copy + _index update, per Atlas brief pattern)."""
import json, os
REPO = "/tmp/na"
OUT = f"{REPO}/partner-pitch/city_briefs"
os.makedirs(OUT, exist_ok=True)
GEN = "2026-07-20"

def brief(cid, display, country, region, tier, tagline, summary, signals, use_cases, journeys,
          pioneer, competitive, seasonality, regulatory, sig_routes, partners, sources, posture, posture_note):
    return {
        "city_id": cid, "display_name": display, "country": country, "region": region, "tier": tier,
        "tagline": tagline, "summary": summary,
        "demand_signals": [{"label": l, "value": v, "source": s} for (l, v, s) in signals],
        "use_cases": [{"archetype": a, "title": t, "body": b, "platform": "Pioneer II"} for (a, t, b) in use_cases],
        "journeys": journeys,
        "navier_fit": {"pioneer_ii": pioneer,
                       "quanta_lr": "Quanta-LR (H2 2026+) is optional here; the core network is well inside Pioneer II all-electric range."},
        "competitive_landscape": competitive, "seasonality": seasonality, "regulatory_note": regulatory,
        "signature_routes": sig_routes, "key_partners": partners,
        "sources": [{"label": s} for s in sources],
        "internal": {"posture": posture, "posture_note": posture_note},
        "_meta": {"generated": GEN, "scan": "mx-eg-expansion-2026-07-20"}, "display": display,
    }

def jr(name, frm, to, nm, today, withn):
    return {"name": name, "from": frm, "to": to, "approx_nm": nm, "platform": "Pioneer II",
            "today": today, "with_navier": withn}

B = []

B.append(brief("isla-holbox-mexico","Isla Holbox","Mexico","LatAm-Caribbean","starter",
  "A celebrated car-free island served today by two competing panga operators — ready for a quieter premium tier.",
  "Isla Holbox is a car-free island at the north of the Yucatán, famous for its quiet sand streets, bioluminescence and whale-shark season. Every visitor arrives by boat across the Chiquilá channel, today on panga-style ferries that run roughly every 30 minutes across two operators. On a short, high-frequency, island-only crossing with no road alternative, a faster, quieter premium tier is a natural fit.",
  [("Access","The only way onto the island is the Chiquilá↔Holbox crossing; no road alternative","Holbox Express / 9 Hermanos schedules"),
   ("Frequency","Two operators run roughly every 30 minutes, ~05:00–22:00","islaholbox-info.com"),
   ("Draw","Car-free island; whale-shark season and bioluminescence draw a premium eco-tourism crowd","Quintana Roo tourism")],
  [("tourism","Premium island crossing","A faster, quieter premium tier over the Chiquilá↔Holbox panga run."),
   ("essential_mobility","Everyday island link","The island's only lifeline for residents, workers and supplies.")],
  [jr("Chiquilá ↔ Isla Holbox","Chiquilá","Isla Holbox",5,
      "A ~30-minute panga crossing every half hour, packed in high season.",
      "A smooth, quiet premium hop to a car-free island with no road alternative.")],
  "Pioneer II owns the Chiquilá↔Holbox crossing (~5 nm) comfortably inside all-electric range.",
  "Two panga operators (Holbox Express, 9 Hermanos) split the crossing; no foiling or premium tier exists — the pain is crowding and wait times in peak season.",
  "Atlantic hurricane season (Jun–Nov) is the constraint; whale-shark season (roughly May–Sep) is peak. The lagoon channel is short and sheltered.",
  "Mexican jurisdiction: API Quintana Roo and the Capitanía de Puerto (SEMAR). Clean-fleet operation aligns with the Yum Balam protected area around Holbox.",
  ["Chiquilá ↔ Isla Holbox (Pioneer II)"],
  ["API Quintana Roo","Holbox Express / 9 Hermanos","Quintana Roo tourism"],
  ["Holbox Express / 9 Hermanos schedules","islaholbox-info.com ferry guide","API Quintana Roo"],
  "P1","Car-free island, single high-frequency crossing, no road alternative"))

B.append(brief("tulum-mexico","Tulum (Puerto Aventuras gateway)","Mexico","LatAm-Caribbean","experiences",
  "High-end Tulum by sea — a luxury charter market and a coastal bypass of the congested Highway 307.",
  "Tulum anchors the boutique-luxury end of the Riviera Maya, but its beach has no formal harbour. The practical sea gateway is Puerto Aventuras, the closest working marina between Tulum and Playa del Carmen and the base for a busy luxury yacht and charter market running across to Cozumel's El Cielo sandbar. For Navier Experiences, this is a premium hospitality-transfer and island-hopping node; a coastal run also bypasses the notoriously congested Highway 307.",
  [("Luxury market","Active luxury yacht/charter market from Puerto Aventuras to Cozumel/El Cielo (charters from ~$950/boat)","Playa Yachting / Cozumel charter operators"),
   ("Road pain","Tulum↔Cancún is a 1.5–2.5 hr drive on the congested, accident-prone Highway 307","Riviera Maya travel guides"),
   ("Hospitality","Tulum's boutique-luxury hotel cluster draws a high-spend, experience-led crowd","Quintana Roo tourism")],
  [("luxury","Tulum ↔ Cozumel Experiences","A premium Navier Experiences run to Cozumel's El Cielo sandbar from the Tulum-side marina."),
   ("tourism","Coastal transfer, Highway 307 bypass","A coastal Puerto Aventuras↔Playa del Carmen run that skips the congested highway.")],
  [jr("Puerto Aventuras ↔ Cozumel (El Cielo)","Puerto Aventuras","Cozumel",12,
      "A luxury yacht charter from ~$950 per boat.",
      "A premium Navier Experiences crossing to the El Cielo sandbar."),
   jr("Puerto Aventuras ↔ Playa del Carmen","Puerto Aventuras","Playa del Carmen",8,
      "A drive up the congested Highway 307.",
      "A quiet coastal transfer bypassing the highway.")],
  "Pioneer II covers the Puerto Aventuras↔Cozumel (~12 nm) and ↔Playa (~8 nm) runs comfortably.",
  "A fragmented luxury-charter market operates today with no scheduled premium tier; the pain is price, fragmentation and Highway 307 congestion on the land alternative.",
  "Atlantic hurricane season (Jun–Nov); sargassum (Apr–Aug) a coastal nuisance. The nearshore corridor is relatively protected.",
  "Mexican jurisdiction: API Quintana Roo, Capitanía de Puerto (SEMAR). Clean-fleet operation aligns with the Mesoamerican Reef's protected status off Cozumel.",
  ["Puerto Aventuras ↔ Cozumel (El Cielo)","Puerto Aventuras ↔ Playa del Carmen"],
  ["Puerto Aventuras marina","Tulum boutique-hotel cluster","Cozumel charter operators"],
  ["Playa Yachting / Cozumel charter market","Riviera Maya travel guides"],
  "P1","Experiences/charter basis; null scheduled economics until a series is pinned"))

B.append(brief("sayulita-riviera-nayarit-mexico","Sayulita & Punta Mita (Riviera Nayarit)","Mexico","LatAm-Pacific","experiences",
  "The Riviera Nayarit's boho-luxury coast — Marietas Islands and coves reached only by boat.",
  "Sayulita and Punta Mita sit at the northern edge of Banderas Bay, a boho-luxury stretch of the Pacific coast. The star waterborne draw is the protected Islas Marietas — famous for the Hidden Beach — reached by permit-controlled boats from the Punta Mita pier, plus coastal hops along the north shore. For Navier Experiences this is a premium island-and-coves node in the same bay as Puerto Vallarta.",
  [("Draw","Islas Marietas (Hidden Beach) is a marquee, permit-controlled boat destination","Punta Mita / Marietas operators"),
   ("Luxury base","Punta Mita's luxury resorts (Four Seasons, One&Only) anchor a high-spend market","Riviera Nayarit tourism"),
   ("Connectivity","Sayulita↔Punta Mita shuttles and water taxis already operate","Sayulita water-taxi operators")],
  [("luxury","Punta Mita ↔ Islas Marietas Experiences","A premium run to the protected Marietas and the Hidden Beach."),
   ("tourism","North-shore coastal hops","Coastal Experiences links across the north of Banderas Bay.")],
  [jr("Punta Mita ↔ Islas Marietas","Punta Mita","Islas Marietas",4,
      "Permit-controlled cooperative pangas.",
      "A premium Navier Experiences run to the protected islands.")],
  "Pioneer II covers the short Marietas and north-shore runs (~4–5 nm) easily.",
  "Cooperative pangas and tour boats operate on permit; no scheduled premium tier exists.",
  "Pacific hurricane season (Jun–Nov); winter–spring is peak. Banderas Bay is large and generally protected.",
  "Mexican jurisdiction: API/Capitanía de Puerto (SEMAR); Islas Marietas is a protected national park with strict visitor permits.",
  ["Punta Mita ↔ Islas Marietas","La Cruz ↔ Punta Mita coastal"],
  ["Marina Riviera Nayarit (La Cruz)","Punta Mita luxury resorts","Islas Marietas park operators"],
  ["Punta Mita / Marietas tour operators","Riviera Nayarit tourism"],
  "P2","Experiences node in the Banderas Bay orbit; null economics"))

B.append(brief("mazatlan-mexico","Mazatlán","Mexico","LatAm-Pacific","starter",
  "The Pearl of the Pacific — a constant daily panga crossing to Stone Island.",
  "Mazatlán is a large Pacific resort and port city with the longest boardwalk in Latin America. Its everyday waterborne corridor is the short crossing from the downtown embarcadero to Isla de la Piedra (Stone Island) — a genuine daily-use panga run for residents and visitors alike, not just a tour. It's a solid display market with a clear signature crossing.",
  [("Draw","Stone Island is a popular daily beach destination reached only by the panga crossing","Stone Island operators"),
   ("Scale","Mazatlán is a major cruise port and one of the Pacific coast's largest resort cities","SECTUR"),
   ("Daily use","The embarcadero↔Stone Island hop runs constantly through the day","local lancha cooperative")],
  [("tourism","Stone Island crossing","A premium tier over the constant Mazatlán↔Isla de la Piedra panga hop."),
   ("essential_mobility","Everyday island link","A daily-use crossing for the island's residents and workers.")],
  [jr("Mazatlán ↔ Isla de la Piedra","Mazatlán (Playa Sur)","Isla de la Piedra",1,
      "A short, constant panga hop.",
      "A quiet, quick premium crossing to Stone Island.")],
  "Pioneer II covers the ~1 nm Stone Island crossing trivially.",
  "Local pangas run the crossing continuously; no premium tier exists. The land alternative is a long road detour around the estuary.",
  "Pacific hurricane season (Jun–Nov); winter is peak cruise season. The estuary crossing is sheltered.",
  "Mexican jurisdiction: API Mazatlán, Capitanía de Puerto (SEMAR).",
  ["Mazatlán ↔ Isla de la Piedra (Stone Island)"],
  ["API Mazatlán","Stone Island lancha cooperative"],
  ["Stone Island lancha operators","SECTUR"],
  "P2","Genuine daily-use crossing; display + brief, null economics"))

B.append(brief("la-paz-mexico","La Paz","Mexico","LatAm-Pacific","experiences",
  "Gateway to Espíritu Santo — a UNESCO island wilderness reached only by boat.",
  "La Paz, capital of Baja California Sur, is the gateway to Isla Espíritu Santo, a protected UNESCO island group of sea-lion colonies, coves and white-sand beaches reached only by permit-controlled boats. For Navier Experiences it's a premium wilderness-island node; the deep-water Pichilingue terminal handles long-haul Gulf ferries and is context only, not a Navier corridor.",
  [("Draw","Isla Espíritu Santo is a marquee UNESCO island-wilderness boat destination","La Paz permit operators"),
   ("Nature","Sea-lion colonies, whale sharks and coves anchor a high-value eco-tourism market","BCS tourism"),
   ("Base","La Paz malecón and marinas provide an established departure base","Marinas de La Paz")],
  [("luxury","La Paz ↔ Espíritu Santo Experiences","A premium run to the protected island group.")],
  [jr("La Paz ↔ Isla Espíritu Santo","La Paz marina","Isla Espíritu Santo",12,
      "Permit-controlled tour pangas.",
      "A premium Navier Experiences run to the UNESCO islands.")],
  "Pioneer II covers the ~12 nm run to Espíritu Santo comfortably.",
  "Permit tour operators serve the island; no premium scheduled tier exists.",
  "Pacific/Gulf hurricane season (Jun–Nov); whale-shark season (Oct–Apr) is a key draw. Gulf waters are generally protected.",
  "Mexican jurisdiction: API/Capitanía de Puerto (SEMAR); Espíritu Santo is a protected area with strict permits.",
  ["La Paz ↔ Isla Espíritu Santo"],
  ["Marinas de La Paz","Espíritu Santo permit operators","BCS tourism"],
  ["La Paz permit tour operators","BCS tourism"],
  "P2","Experiences node; null economics"))

B.append(brief("acapulco-mexico","Acapulco","Mexico","LatAm-Pacific","starter",
  "A classic bay city with a constant Caleta↔Roqueta crossing.",
  "Acapulco is a historic Pacific bay resort. Its everyday waterborne corridor is the short, popular hop from Playa Caleta out to Isla de la Roqueta — a constant daily-use panga and glass-bottom-boat crossing — plus bay hops along the malecón. It's a display market with a clear signature crossing. Security conditions in Guerrero vary and should be represented honestly to partners.",
  [("Draw","Isla de la Roqueta is a popular island destination off the bay, reached by frequent pangas","Caleta/Roqueta operators"),
   ("Bay","Acapulco Bay is a large, sheltered natural harbour with waterfront traffic","Municipal"),
   ("Heritage","A long-established resort city with strong domestic tourism","SECTUR")],
  [("tourism","Caleta ↔ Roqueta crossing","A premium tier over the constant bay crossing to Roqueta Island."),
   ("essential_mobility","Bay hops","Waterfront hops across the sheltered bay.")],
  [jr("Playa Caleta ↔ Isla de la Roqueta","Playa Caleta","Isla de la Roqueta",1,
      "Frequent pangas and glass-bottom boats.",
      "A quiet premium crossing across the bay.")],
  "Pioneer II covers the ~1 nm Roqueta crossing and bay hops trivially.",
  "Local pangas and glass-bottom boats serve the crossing; no premium tier exists.",
  "Pacific hurricane season (Jun–Nov). The bay is a large, sheltered natural harbour. Note: security conditions in Guerrero vary and are represented honestly to partners.",
  "Mexican jurisdiction: API Acapulco, Capitanía de Puerto (SEMAR).",
  ["Playa Caleta ↔ Isla de la Roqueta"],
  ["API Acapulco","Caleta/Roqueta lancha cooperative"],
  ["Caleta/Roqueta operators","SECTUR"],
  "P2","Display; null economics; honest security framing"))

B.append(brief("puerto-escondido-mexico","Puerto Escondido","Mexico","LatAm-Pacific","experiences",
  "Oaxaca's surf capital — coastal Experiences and the bioluminescent Manialtepec lagoon.",
  "Puerto Escondido is Oaxaca's famous surf town, and while its beaches are surf-access, it carries a real Experiences waterborne market: dolphin and turtle boat trips from Playa Principal and the bioluminescent Laguna de Manialtepec ~18 km west. For scheduled transit, the genuine Oaxaca-coast node is nearby Huatulco (see separate brief). Here the fit is premium coastal and lagoon Experiences.",
  [("Draw","The Manialtepec coastal lagoon is famous for bioluminescence and birdlife boat trips","Manialtepec operators"),
   ("Surf","Zicatela is a world-class surf beach anchoring a strong tourism draw","Oaxaca tourism"),
   ("Wildlife","Dolphin and turtle boat trips run from the main beach","local lancha cooperative")],
  [("tourism","Manialtepec lagoon Experiences","A premium Navier Experiences run to the bioluminescent lagoon."),
   ("luxury","Coastal wildlife Experiences","Premium dolphin/turtle coastal runs from the main beach.")],
  [jr("Puerto Escondido ↔ Laguna de Manialtepec","Puerto Escondido","Manialtepec lagoon",9,
      "Lancha cooperative day and night tours.",
      "A premium Navier Experiences run to the lagoon.")],
  "Pioneer II covers the ~9 nm coastal run to Manialtepec comfortably.",
  "Lancha cooperatives run tours; no premium scheduled tier exists.",
  "Pacific hurricane season (Jun–Nov); the coast has strong surf swell year-round (a routing consideration).",
  "Mexican jurisdiction: API/Capitanía de Puerto (SEMAR); Manialtepec is an ecologically sensitive lagoon.",
  ["Puerto Escondido ↔ Laguna de Manialtepec"],
  ["Manialtepec lagoon cooperative","Oaxaca tourism"],
  ["Manialtepec tour operators","Oaxaca tourism"],
  "P2","Experiences/lagoon basis; null economics"))

B.append(brief("huatulco-mexico","Bahías de Huatulco","Mexico","LatAm-Pacific","starter",
  "Nine bays, most reachable only by boat — the real transit node of the Oaxaca coast.",
  "Bahías de Huatulco is a FONATUR-planned resort spanning nine bays and dozens of beaches, most of which are reachable only by boat. A water-taxi network runs from Santa Cruz Marina out to the bays (Maguey, El Órgano, Cacaluta and more), and a larger pier is under construction. This is the genuine scheduled-transit node of the Oaxaca coast and a strong full/display market with a clear signature service.",
  [("Access","Most of the nine bays and 36 beaches are reachable only by boat","Bahías de Huatulco guides"),
   ("Network","An established water-taxi network departs Santa Cruz Marina; a larger pier is under construction","Marinautica Huatulco"),
   ("Planned resort","A FONATUR master-planned resort with organized tourism infrastructure","FONATUR")],
  [("tourism","Nine-bays water-taxi network","A premium tier over the Santa Cruz↔bays water-taxi service."),
   ("essential_mobility","Boat-only bay access","The only practical way to reach most of the bays.")],
  [jr("Santa Cruz Marina ↔ the Nine Bays","Santa Cruz Marina","Bahía Maguey / El Órgano / Cacaluta",4,
      "A shared water-taxi network from the marina.",
      "A premium, quiet tier to the boat-only bays.")],
  "Pioneer II covers the nine-bays runs (~4 nm) easily.",
  "A water-taxi cooperative serves the bays from Santa Cruz Marina; no premium tier exists. The pain is capacity and comfort at peak.",
  "Pacific hurricane season (Jun–Nov); winter is peak. The bays are protected coves.",
  "Mexican jurisdiction: API/FONATUR, Capitanía de Puerto (SEMAR); the bays include protected national-park waters.",
  ["Santa Cruz Marina ↔ the Nine Bays"],
  ["FONATUR / API","Marinautica Huatulco","Santa Cruz water-taxi cooperative"],
  ["Marinautica Huatulco","Bahías de Huatulco guides","FONATUR"],
  "P1","Genuine boat-only bay network; the Oaxaca-coast transit anchor"))

B.append(brief("alexandria-egypt","Alexandria","Egypt","MENA","starter",
  "Egypt's Mediterranean capital — a Corniche sea line above chronic seafront traffic.",
  "Alexandria is Egypt's second city and principal Mediterranean seaport, a dense urban coast wrapped around the historic Eastern Harbour beneath the Qaitbay Citadel. Its long Corniche suffers chronic seafront congestion, and local pleasure craft already work the harbour. A sea line along the Corniche — from the Eastern Harbour to the Montaza gardens — offers a scenic premium tier above the traffic. There is no regulated scheduled passenger series today, so this is a display + rich-brief market with null economics until a series is found.",
  [("Urban scale","Egypt's second-largest city and primary Mediterranean seaport","Egyptian government"),
   ("Waterfront","A long Corniche with heavy seafront traffic and active local pleasure craft","Alexandria corniche"),
   ("Heritage","Qaitbay Citadel, Montaza gardens and the Bibliotheca anchor a strong tourism draw","Egypt tourism")],
  [("tourism","Corniche sea line","A scenic premium tier along the Corniche, above the seafront traffic."),
   ("essential_mobility","Harbour and bay hops","Short hops across the Eastern Harbour and east toward Montaza/Abu Qir.")],
  [jr("Eastern Harbour ↔ Montaza","Eastern Harbour (Anfoushi)","Montaza",9,
      "A slow drive along the congested Corniche.",
      "A scenic premium sea line bypassing seafront traffic.")],
  "Pioneer II covers the Corniche run (~9 nm) and harbour hops comfortably.",
  "Local pleasure craft work the harbour; there is no scheduled premium passenger tier. The pain is Corniche road congestion.",
  "Mediterranean summer (Jun–Sep) is peak; winter storms are a constraint. The Eastern Harbour is a sheltered crescent.",
  "Egyptian jurisdiction: the Alexandria Port Authority and the maritime authority. Clean-fleet operation suits a dense urban seafront.",
  ["Eastern Harbour ↔ Montaza (Corniche)","Eastern Harbour ↔ Qaitbay"],
  ["Alexandria Port Authority","Egypt tourism"],
  ["Alexandria corniche / local craft","Egypt tourism"],
  "P2","Thin→full display; null economics unless a regulated series is found"))

B.append(brief("marsa-alam-wadi-el-gemal-egypt","Marsa Alam & Wadi El Gemal","Egypt","MENA","starter",
  "Boat-only access to a protected Red Sea national park — the same near-monopoly logic as Giftun.",
  "Marsa Alam is the southern Red Sea's remote, pristine resort coast, and its marquee waterborne draw is Wadi El Gemal National Park: the Qulaan/Hamata island archipelago (Siyul, Showarit, Um El Sheikh), reachable only by boat from Hamata Marina. This is the same boat-only, near-monopoly access pattern that anchors the Giftun corridors up the coast at Hurghada — a strong candidate for economics once park-permit and operator volumes are pinned.",
  [("Access","The Qulaan/Hamata islands inside Wadi El Gemal are reachable only by boat","Wadi El Gemal operators"),
   ("Protected","A national park with permit-gated, boat-only island access","Wadi El Gemal National Park"),
   ("Pristine","Remote southern Red Sea reef, dugongs and sea turtles draw high-value eco-tourism","Egypt tourism")],
  [("tourism","Wadi El Gemal island Experiences","A premium tier to the protected Qulaan/Hamata islands."),
   ("essential_mobility","Boat-only park access","The only way to reach the park's islands.")],
  [jr("Hamata ↔ Qulaan Islands","Hamata Marina","Qulaan / Hamata islands",7,
      "Full-day boat trips into the park.",
      "A premium, quiet tier to the protected islands.")],
  "Pioneer II covers the ~7 nm Hamata↔Qulaan run comfortably.",
  "Boat operators run full-day park trips; access is boat-only and permit-gated — a near-monopoly access corridor with no premium tier today.",
  "Red Sea is warm and diveable year-round; summer heat is extreme. Southern reef waters are generally calm.",
  "Egyptian jurisdiction: the maritime authority and the Wadi El Gemal National Park administration (permit-gated).",
  ["Hamata ↔ Qulaan Islands (Wadi El Gemal)"],
  ["Wadi El Gemal National Park","Hamata boat operators","Egypt tourism"],
  ["Wadi El Gemal / Hamata operators","Egypt tourism"],
  "P1","Boat-only park corridor; conditional economics once permit/operator volumes are pinned"))

B.append(brief("dahab-egypt","Dahab","Egypt","MENA","experiences",
  "Sinai's laid-back dive town — boat access to Blue Hole and Gabr El Bint.",
  "Dahab is a laid-back Sinai coastal town, world-famous for freediving and shore-diving sites. Its waterborne draw is boat access along the shore to sites such as Gabr El Bint and the Blue Hole area. For Navier Experiences it's a premium dive-and-coast node; there is no scheduled transit series, so economics are null.",
  [("Draw","World-famous freediving and shore-diving sites (Blue Hole, Gabr El Bint)","Dahab dive community"),
   ("Charter","Boat access to shore-only dive sites is an active local market","Dahab dive operators"),
   ("Vibe","A backpacker/boho coast distinct from the Sinai mega-resorts","Egypt tourism")],
  [("luxury","Dahab coastal dive Experiences","A premium run along the Sinai shore to boat-access dive sites.")],
  [jr("Dahab ↔ Gabr El Bint / Blue Hole","Dahab lagoon","Gabr El Bint",4,
      "Local dive boats.",
      "A premium Navier Experiences run along the shore.")],
  "Pioneer II covers the short Sinai-shore runs (~4 nm) easily.",
  "Local dive boats serve the sites; no premium tier exists.",
  "Red Sea/Gulf of Aqaba is diveable year-round; summer heat is extreme. Aqaba waters are sheltered.",
  "Egyptian jurisdiction: the maritime authority; the coast borders protected reef areas.",
  ["Dahab ↔ Gabr El Bint / Blue Hole"],
  ["Dahab dive operators","Egypt tourism"],
  ["Dahab dive/boat operators","Egypt tourism"],
  "P2","Experiences basis; null economics"))

for b in B:
    json.dump(b, open(f"{OUT}/{b['city_id']}.json","w"), indent=2, ensure_ascii=False)
print(f"wrote {len(B)} city briefs")
for b in B: print("  ", b["city_id"])
