import {describe,expect,test} from 'bun:test';
import {makeTaskletNativePort,type ToolCaller} from '../adapters/tasklet';
const ids={slides:'fixture_slides_connection',drive:'fixture_drive_connection'};
function fixture(){const calls:any[]=[];const invoke:ToolCaller=async(request)=>{calls.push(request);const {toolName,args}=request;let data:any;if(toolName==='google_slides_get_presentation')data=args.mode==='summary'?{presentationId:args.presentationId,title:'Fixture',slideCount:3,pageSize:{width:{magnitude:720,unit:'PT'},height:{magnitude:405,unit:'PT'}}}:{slides:[{objectId:`slide_${(args.slideIndices as number[])[0]}`,pageElements:[],slideProperties:{notesPage:{notesProperties:{speakerNotesObjectId:'notes_fixture'}}}}]};else if(toolName==='google_slides_create_presentation')data={presentationId:'created_fixture',webViewLink:'https://example.invalid/created'};else if(toolName==='google_drive_duplicate_file')data={fileId:'copy_fixture',webViewLink:'https://example.invalid/copy'};else data={success:true};return{ok:true,json:async()=>data};};return {calls,port:makeTaskletNativePort(ids,invoke)};}
describe('optional Tasklet adapter',()=>{
 test('reads summary then ordered complete slide records with notes',async()=>{const {calls,port}=fixture();const s=await port.snapshot('deck_fixture');expect(s.slides.map(x=>x.objectId)).toEqual(['slide_1','slide_2','slide_3']);expect(s.slides.every(x=>!!x.slideProperties.notesPage)).toBe(true);expect(calls).toHaveLength(4);expect(calls.every(c=>c.connectionId===ids.slides)).toBe(true);});
 test('maps create, backup, batch and PDF export to explicit connections',async()=>{const {calls,port}=fixture();expect((await port.create('Fixture')).presentationId).toBe('created_fixture');expect((await port.duplicate('deck_fixture','Backup')).presentationId).toBe('copy_fixture');await port.batch('copy_fixture',[{insertText:{objectId:'text_fixture',text:'Fixture'}}]);await port.exportPDF!('copy_fixture','/private-workspace/review.pdf');expect(calls.map(c=>c.connectionId)).toEqual([ids.slides,ids.drive,ids.slides,ids.drive]);expect(calls.at(-1).args.exportMimeType).toBe('application/pdf');});
 test('refuses conditional writes without making a call and propagates failures',async()=>{const {calls,port}=fixture();expect(port.conditionalRevisions).toBe(false);await expect(port.batch('deck_fixture',[],'revision_fixture')).rejects.toThrow(/conditional/);expect(calls).toHaveLength(0);const bad=makeTaskletNativePort(ids,async()=>({ok:false,error:'Fixture failure',json:async()=>{throw new Error('must not read failed response');}}));await expect(bad.snapshot('fixture')).rejects.toThrow('Fixture failure');expect(()=>makeTaskletNativePort({slides:'',drive:''},async()=>({ok:true,json:async()=>({})}))).toThrow(/Explicit/);});
});
